### ISSUE TITLE
navbar-brand image takes up majority of the page

### ISSUE THREAD

**Issue by simplyhexagon** [CosmosOS/cosmosos.github.io#2]
- Browser: Brave 1.47.186 Chromium: 109.0.5414.119
- OS: Win11 Pro x64
- Resolution: 1920x1080

Problem: When browsing the website, I can't change the options, because the Cosmos logo (`navbar-brand` in code), takes up 1/3 of the page
![Screenshot](https://user-images.githubusercontent.com/40917873/215283279-0e8b330f-53b0-4020-9937-fcf68625c02d.png)

**Comment by 9xbt** [comment]
It's now fixed :D

**Comment by simplyhexagon** [comment]
Checked in browser and on mobile, it works perfectly
